name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.7.0 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node
      - name: Install dependencies
        run: npm install
      - name: Lint the code
        run: npm run lint
      - name: Run tests
        run: npm test
        env:
          VITE_NOROFF_API_KEY: ${{ secrets.API_KEY }}
      - name: Build project
        run: npm run build
        env:
          VITE_NOROFF_API_KEY: ${{ secrets.API_KEY }}
